import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    width: "100%",
    minHeight: "100vh",
    background: "#f2f2f2",
    display: "flex",
    justifyContent: "center",
    padding: "20px 12px 40px",
    boxSizing: "border-box",
  },
  container: {
    width: "100%",
    maxWidth: "480px",
  },
  card: {
    background: "#fff",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
    padding: "14px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  back: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    background: "transparent",
    border: "none",
    color: "#E53935",
    fontWeight: 600,
    cursor: "pointer",
  },
  identidade: {
    display: "grid",
    gridTemplateColumns: "48px 1fr",
    gap: "12px",
    alignItems: "center",
  },
  logo: {
    height: "48px",
    width: "48px",
    borderRadius: "50%",
    color: "#fff",
    display: "grid",
    placeItems: "center",
    fontWeight: 800,
    fontFamily:
      "system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
  },
  nome: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#212121",
  },
  divider: {
    height: "1px",
    background: "#EEEEEE",
    margin: "2px 0",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "center",
    padding: "10px 0",
  },
  rowLabel: {
    color: "#757575",
  },
  rowValue: {
    color: "#424242",
    display: "flex",
    alignItems: "baseline",
    gap: "6px",
  },
  rowValueStrong: {
    color: "#E53935",
  },
  sub: {
    color: "#9E9E9E",
    marginLeft: "4px",
    fontSize: "13px",
  },
  cta: {
    marginTop: 6,
    backgroundColor: "#E53935",
    color: "#fff",
    borderWidth: 0,
    borderRadius: 6,
    padding: 12,
    fontWeight: "700",
  },
  box: {
    width: "97%",
    height: 80,
    backgroundColor: "#fff",
    borderRadius: 8,
    marginVertical: 5,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  largeBox: {
    height: 'auto',
    padding: 15,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  icon: {
    width: 24,
    height: 24,
    marginRight: 10,
  },
  smallIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  text: {
    fontSize: 18,
    fontWeight: '600',
  },
  label: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  input: {
    backgroundColor: '#f5f5f5',
    borderRadius: 4,
    height: 40,
    paddingHorizontal: 10,
  },
  inputInline: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    borderRadius: 4,
    height: 40,
    paddingHorizontal: 10,
    marginLeft: 10,
    justifyContent: 'center',
  },
  columnText: {
    fontSize: 14,
    color: '#666',
    width: 100,
  },
  dashedBox: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#999',
    borderRadius: 8,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  addPhotoText: {
    color: '#999',
    fontSize: 14,
  },
  preview: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    margin: 20,
    borderRadius: 8,
    padding: 20,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 15,
    textAlign: 'center',
  },
  categoryItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  cancelButton: {
    marginTop: 15,
    backgroundColor: '#E53935',
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '97%',
    marginTop: 20,
    paddingHorizontal: 15,
  },
  saveButton: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#EA3F24',
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 12,
    marginRight: 8,
    alignItems: 'center',
  },
  saveText: {
    color: '#EA3F24',
    fontSize: 16,
    fontWeight: '600',
  },
  publishButton: {
    flex: 1,
    backgroundColor: '#EA3F24',
    borderRadius: 10,
    paddingVertical: 12,
    marginLeft: 8,
    alignItems: 'center',
  },
  publishText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  disabledButton: {
    backgroundColor: '#ccc',
  },
  helpText: {
    marginTop: 8,
    color: '#666',
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 15,
  },
});

export default { styles }