export const styles = {
  root: {
    width: "100%",
    minHeight: "100vh",
    background: "#f2f2f2",
    display: "flex",
    justifyContent: "center",
    padding: "20px 12px 40px",
    boxSizing: "border-box",
  },
  container: {
    width: "100%",
    maxWidth: "480px",
  },
  card: {
    background: "#fff",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
    padding: "14px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  back: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    background: "transparent",
    border: "none",
    color: "#E53935",
    fontWeight: 600,
    cursor: "pointer",
  },
  identidade: {
    display: "grid",
    gridTemplateColumns: "48px 1fr",
    gap: "12px",
    alignItems: "center",
  },
  logo: {
    height: "48px",
    width: "48px",
    borderRadius: "50%",
    color: "#fff",
    display: "grid",
    placeItems: "center",
    fontWeight: 800,
    fontFamily:
      "system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
  },
  nome: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#212121",
  },
  divider: {
    height: "1px",
    background: "#EEEEEE",
    margin: "2px 0",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "center",
    padding: "10px 0",
  },
  rowLabel: {
    color: "#757575",
  },
  rowValue: {
    color: "#424242",
    display: "flex",
    alignItems: "baseline",
    gap: "6px",
  },
  rowValueStrong: {
    color: "#E53935",
  },
  sub: {
    color: "#9E9E9E",
    marginLeft: "4px",
    fontSize: "13px",
  },
  cta: {
    marginTop: "6px",
    background: "#E53935",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    padding: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
};
